Adapter fail'
AlexeyGvozdev/TodoApp pull request #10
Opened 2023-01-20 08:48 UTC by Fail-Salikhov

2023-01-22 21:05 UTC, chandrey34 commented on task/src/main/res/layout/task_list_layout.xml
> +        android:textSize="24dp"
у текста размер в sp

2023-01-22 21:12 UTC, chandrey34 commented on task/src/main/res/layout/item_task_manager.xml
> +            android:text="07 Jan 23 / Project"
tools:text, текст который тут укажешь будет виден в студии но не виден в приложении

2023-01-22 21:12 UTC, chandrey34 commented on task/src/main/res/layout/item_task_manager.xml
> +            android:textSize="16dp"
размер текста в sp

2023-01-22 21:12 UTC, chandrey34 commented on task/src/main/res/layout/item_task_manager.xml
> +            android:text="Task Manager"
tools:text

2023-01-22 21:20 UTC, chandrey34 commented on task/src/main/res/layout/task_list_layout.xml
> +        android:layout_height="0dp"
почему 0dp, а не wrap_content ?

2023-01-22 21:33 UTC, chandrey34 commented on task/src/main/res/layout/task_list_layout.xml
> +        app:layoutManager="androidx.recyclerview.widget.LinearLayoutManager"
почему именно тут указываешь это? 
обычно Фрагменте, в твоем случае в TaskListFragment в fun onViewCreated

``` 
binding.rvTaskList.layoutManager = LinearLayoutManager(context)
binding.rvTaskList.adapter = taskListAdapter
taskListAdapter.submitList(taskList)
```

2023-01-23 08:02 UTC, Fail-Salikhov commented on task/src/main/res/layout/task_list_layout.xml
> +        android:textSize="24dp"
поправил)

2023-01-23 08:03 UTC, Fail-Salikhov commented on task/src/main/res/layout/item_task_manager.xml
> +            android:textSize="16dp"
поправил)

2023-01-23 08:04 UTC, Fail-Salikhov commented on task/src/main/res/layout/item_task_manager.xml
> +            android:text="07 Jan 23 / Project"
не использовал так как и так было видно в студии

2023-01-23 08:08 UTC, Fail-Salikhov commented on task/src/main/res/layout/task_list_layout.xml
> +        app:layoutManager="androidx.recyclerview.widget.LinearLayoutManager"
да, знаю что там тоже можно указывать. По мне так удобнее и логичнее указывать в файле xml.

2023-01-23 10:25 UTC, NatalyTsivileva reviewed
Есть замечания, указаны в комментариях кода

2023-01-23 10:25 UTC, NatalyTsivileva commented on task/src/main/java/com/sinx/task/adapter/TaskListAdapter.kt
> +    var onMoreItemClickListener:((TaskItem) -> Unit)? = null
Удалить. 
Вместо этих функций в конструктор TaskListAdapter лучше передать что-то, что реализует интерфейс типа:

    interface OnTaskClickListener {
       fun onMoreItemClick(item:TaskItem)
	   fun onCheckBoxItemClick(item:TaskItem, isChecked:Boolean)
    }

Чтобы было так: 

    class TaskListAdapter(
        var listener: OnTaskClickListener
    ) : ListAdapter<TaskItem, TaskListAdapter.TaskItemViewHolder>(TaskItemDiffCallback()){...

И тогда во фрагменте инициализация будет выглядеть так:

    private val taskListAdapter by lazy {
        TaskListAdapter(object :OnTaskClickListener{
            override fun onMoreItemClick(item: TaskItem) {
                //Нажали на больше
            }

            override fun onCheckBoxItemClick(item: TaskItem, isChecked: Boolean) {
                //Выбрали итем
            }
        })
        }

2023-01-23 10:25 UTC, NatalyTsivileva commented on task/src/main/java/com/sinx/task/model/TaskItem.kt
> +    var id : Int = UNDEFINED_ID,
var изменить на val. Id не должен меняться со временем

2023-01-23 10:25 UTC, NatalyTsivileva commented on task/src/main/res/layout/task_list_layout.xml
> +        app:layoutManager="androidx.recyclerview.widget.LinearLayoutManager"
Можно и там и там. Если не планируется использовать этот же Recycler View в другой разметке то можно указать прямо в файле layout, если планируется, то лучше программно

2023-01-23 10:45 UTC, Fail-Salikhov commented on build.gradle
> +    id "com.android.application" version '7.4.0' apply false
это студия меняла. Менять нет необходимости

2023-01-23 14:14 UTC, NatalyTsivileva approved these changes
Всё хорошо

2023-01-23 14:38 UTC, AlexeyGvozdev requested changes

2023-01-23 14:38 UTC, AlexeyGvozdev commented on task/src/main/java/com/sinx/task/TaskListFragment.kt
> +            override fun onMoreItemClickListener(item: TaskItem) {
можно проще написать TaskListAdapter { 
// TODO("Not yet implemented")
 }

2023-01-23 14:38 UTC, AlexeyGvozdev commented on task/src/main/java/com/sinx/task/adapter/TaskListAdapter.kt
> +    class TaskItemViewHolder(
Холдер в отдельный файл вынеси

2023-01-23 14:38 UTC, AlexeyGvozdev commented on task/src/main/res/drawable/baseline_drag_indicator_24.xml
> +<vector android:height="24dp" android:tint="#A7A7A7"
в кор модуль

2023-01-23 14:38 UTC, AlexeyGvozdev commented on task/src/main/res/font/inter_semibold.xml
> +<?xml version="1.0" encoding="utf-8"?>
в кор модуль

2023-01-23 14:38 UTC, AlexeyGvozdev commented on task/src/main/res/layout/task_list_layout.xml
> +        app:layoutManager="androidx.recyclerview.widget.LinearLayoutManager"
пусть тут будет, пока не принципиально

2023-01-23 14:38 UTC, AlexeyGvozdev commented on task/src/main/res/values/colors.xml
> +<resources>
в кор модуль

2023-01-23 14:38 UTC, AlexeyGvozdev commented on task/src/main/res/values/font_certs.xml
> +<?xml version="1.0" encoding="utf-8"?>
в кор модуль

2023-01-24 08:58 UTC, AlexeyGvozdev approved these changes

2023-01-24 09:12 UTC, merged