#TASK-32 initial commit
AlexeyGvozdev/TodoApp pull request #12
Opened 2023-01-20 15:41 UTC by NatalyTsivileva

2023-01-20 21:21 UTC, AlexeyGvozdev commented
Давай build.gradle в корне проекта тоже переведём на kts

2023-01-20 21:21 UTC, AlexeyGvozdev requested changes

2023-01-20 21:21 UTC, AlexeyGvozdev commented on project/build.gradle.kts
> +    compileSdk = 33
Давай эти все значения тоже вынесем в buildSrc

2023-01-21 14:16 UTC, NatalyTsivileva commented on project/build.gradle.kts
> +    compileSdk = 33
хорошо)

2023-01-22 16:17 UTC, Fail-Salikhov approved these changes

2023-01-22 16:19 UTC, Fail-Salikhov approved these changes

2023-01-22 18:26 UTC, AlexeyGvozdev approved these changes

2023-01-23 08:41 UTC, merged