TASK-14 add adapter and display a list of tasks on the mock data
AlexeyGvozdev/TodoApp pull request #19
Opened 2023-01-26 16:01 UTC by Fail-Salikhov

2023-01-29 13:02 UTC, AlexeyGvozdev requested changes

2023-01-29 13:02 UTC, AlexeyGvozdev commented on task/src/main/res/layout/task_list_layout.xml
> +            android:text="Today"
В ресурсы

2023-01-29 15:05 UTC, Fail-Salikhov commented on task/src/main/res/layout/task_list_layout.xml
> +            android:text="Today"
ок, сдклал

2023-01-30 18:58 UTC, chandrey34 commented on task/src/main/res/layout/item_task_manager.xml
> +        android:text="@string/_07_jan_23_project_example"
это не надо выносить в ресурс стринг, сейчас используем моковые данные, сделай tools:text = "твой текст который считаешь нужным"

2023-01-30 18:59 UTC, chandrey34 commented on task/src/main/res/values/strings.xml
> +    <string name="_07_jan_23_project_example">07 Jan 23 / Project</string>
удалить

2023-01-30 18:59 UTC, chandrey34 commented on task/src/main/res/values/strings.xml
> +    <string name="task_manager_example">Task Manager</string>
удалить

2023-01-30 19:00 UTC, chandrey34 commented on task/src/main/res/layout/item_task_manager.xml
> +        android:text="@string/task_manager_example"
это не надо выносить в ресурс стринг, сейчас используем моковые данные, сделай tools:text = "твой текст который считаешь нужным"

2023-01-30 19:04 UTC, chandrey34 approved these changes
не критичные замечания, внеси и как я понял Алексей сказал можно мержить (если я не перепутал пр к которому это относилось)

2023-02-02 11:50 UTC, AlexeyGvozdev approved these changes

2023-02-02 11:54 UTC, merged