TASK_6_add_separator_via_decorator
AlexeyGvozdev/TodoApp pull request #22
Opened 2023-01-26 22:13 UTC by chandrey34

Добавил DividerItemDecorator

2023-01-26 22:16 UTC, chandrey34 commented on project/src/main/java/com/sinx/project/ProjectFragment.kt
> +
пустую строку удалил

2023-01-26 22:16 UTC, chandrey34 commented on project/src/main/java/com/sinx/project/ProjectFragment.kt
>          return binding.root
поднял return на 34

2023-01-27 20:01 UTC, NatalyTsivileva requested changes
Есть критичные замечания

2023-01-28 11:39 UTC, AlexeyGvozdev requested changes

2023-01-28 11:39 UTC, AlexeyGvozdev commented on project/src/main/java/com/sinx/project/decoration/DividerItemDecoration.kt
> +        const val DIVIDER_LEFT = 88
я бы сделал декоратор максимально тупым и настраиваемым, чтобы на других экранах его можно было переиспользовать.  Не надо передавать контекст, передавай сразу drawable

2023-01-28 13:51 UTC, chandrey34 commented on project/src/main/java/com/sinx/project/decoration/DividerItemDecoration.kt
> +                val dividerTop: Int = child.bottom + params.bottomMargin
с другими правками сейчас пытаюсь разобраться, по поводу верстки - не понимаю что именно не корректно, по мне так все элементы отображаются

2023-01-28 15:09 UTC, chandrey34 commented on project/src/main/java/com/sinx/project/decoration/DividerItemDecoration.kt
> +                val dividerTop: Int = child.bottom + params.bottomMargin
верстку поправил, сделал корректно и с вложенным Constraint Layout и без него, оставил второй вариант
остальное пока пытаюсь разобрать

2023-01-29 16:54 UTC, Fail-Salikhov approved these changes

2023-01-29 16:59 UTC, Fail-Salikhov approved these changes

2023-01-30 19:30 UTC, chandrey34 commented on project/src/main/java/com/sinx/project/decoration/DividerItemDecoration.kt
> +        const val DIVIDER_LEFT = 88
по поводу того, чтобы декоратор брал отступы слева и справа у родительской вью - согласен, возможно это было бы лучшим решением, и я тестил его у себя, но на некоторых экранах в данном проекте разделитель будет по размеру меньше, чем вью, соответстенно я оставляю прямое указание отступов, чтобы можно было легко сделать для других экранов

2023-01-30 19:31 UTC, chandrey34 commented on project/src/main/java/com/sinx/project/decoration/DividerItemDecoration.kt
> +    private val mDivider: Drawable = ContextCompat.getDrawable(context, resId)!!
ок, постараюсь избегать

2023-01-31 06:49 UTC, NatalyTsivileva commented on project/src/main/java/com/sinx/project/decoration/DividerItemDecoration.kt
> +        for (i in 0 until parent.childCount - 2) {
Речь не о моих предпочтениях в кодинге. Даже если ты оставишь как есть, т.е for (i in 0 until parent.childCount - 2) это будет работать неправильно.

2023-01-31 06:51 UTC, chandrey34 commented on project/src/main/java/com/sinx/project/decoration/DividerItemDecoration.kt
> +        for (i in 0 until parent.childCount - 2) {
(i in 0 until parent.childCount - 2) - я согласен, это некорректно, -2 было т.к ресайклер не все итемы отрисовывал, я скорректировал все )

2023-01-31 07:08 UTC, NatalyTsivileva commented on project/src/main/java/com/sinx/project/decoration/DividerItemDecoration.kt
> +        for (i in 0 until parent.childCount - 2) {
Хорошо, сравни 2 видео 
[1.webm](https://user-images.githubusercontent.com/33492646/215690366-7105f347-6162-4108-9e7e-552aeed53028.webm)
[2.webm](https://user-images.githubusercontent.com/33492646/215690389-223265fd-83d3-48b6-beae-489d5d5a24da.webm)

2023-01-31 07:12 UTC, chandrey34 commented on project/src/main/java/com/sinx/project/decoration/DividerItemDecoration.kt
> +        for (i in 0 until parent.childCount - 2) {
у меня отрисовывается именно так как на 2 видео, я поэтому и не понимал в чем проблема. вечером могу даже видео записатьь, скажи, а ты какой код запускала в 1 видео, тот что с последними изменениями?https://github.com/AlexeyGvozdev/TodoApp/pull/22/commits/2de4ede138640c604a418e03d20fc1b2b52bcb21 ?

2023-01-31 07:18 UTC, NatalyTsivileva commented on project/src/main/java/com/sinx/project/decoration/DividerItemDecoration.kt
> +        for (i in 0 until parent.childCount - 2) {
Да, сейчас вижу, что работает корректно.
@AlexeyGvozdev , почему могу не видеть последние изменения по своим замечаниям ни переходя по ссылке https://github.com/AlexeyGvozdev/TodoApp/pull/22, ни нажимая на кнопку с замечаниями:
![image](https://user-images.githubusercontent.com/33492646/215692444-e24d1c33-2258-4963-8995-09c3e6d0fd19.png)
?

2023-01-31 07:21 UTC, NatalyTsivileva approved these changes

2023-01-31 18:36 UTC, AlexeyGvozdev approved these changes

2023-02-01 20:57 UTC, chandrey34 commented on .idea/compiler.xml
> +    <bytecodeTargetLevel target="19" />
добавила студия

2023-02-01 20:57 UTC, chandrey34 commented on .idea/misc.xml
> +  <component name="ProjectRootManager" version="2" languageLevel="JDK_X" project-jdk-name="Android Studio default JDK" project-jdk-type="JavaSDK">
добавила студия

2023-02-01 20:57 UTC, chandrey34 commented on .idea/gradle.xml
> +        <option name="gradleJvm" value="openjdk-19" />
добавила студия

2023-02-02 20:24 UTC, merged