Task 7 project creation window
AlexeyGvozdev/TodoApp pull request #23
Opened 2023-01-28 11:39 UTC by Fail-Salikhov

2023-01-30 18:38 UTC, chandrey34 approved these changes

2023-01-30 18:39 UTC, Fail-Salikhov commented on project/src/main/res/values/strings.xml
>      <string name="titleProject">Projects</string>
поправил)

2023-02-01 15:34 UTC, AlexeyGvozdev requested changes

2023-02-01 15:34 UTC, AlexeyGvozdev commented on app/src/main/AndroidManifest.xml
> +            <nav-graph android:value="@navigation/project_add_new_graph" />
Скажи, зачем нам это?

2023-02-01 15:34 UTC, AlexeyGvozdev commented on app/src/main/res/navigation/project_add_new_graph.xml
> +            app:uri="app://project.BottomSheetAddProjectFragment" />
Хочется, чтобы мы одинаково для всех экранов называли диплинки

2023-02-01 15:34 UTC, AlexeyGvozdev commented on project/src/main/res/layout/project_layout.xml
> +        app:backgroundTint="@color/black"
так как эта кномпка много где будет использоваться. Давай её вынесем в отдельный лейаут в кор, а тут будем через include подключать

2023-02-02 13:40 UTC, Fail-Salikhov commented on app/src/main/AndroidManifest.xml
> +            <nav-graph android:value="@navigation/project_add_new_graph" />
убрал, видел на https://startandroid.ru/ru/courses/architecture-components/27-course/architecture-components/561-urok-28-navigation-vlozhennyj-graf.html он указывал. убрал, все работает

2023-02-02 13:41 UTC, Fail-Salikhov commented on project/src/main/res/layout/project_layout.xml
> +        app:backgroundTint="@color/black"
сделал

2023-02-02 18:18 UTC, AlexeyGvozdev requested changes

2023-02-02 18:18 UTC, AlexeyGvozdev commented on core/src/main/res/layout/add_button.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
Тут не так надо делать, здесь лучше через <merge сделать

2023-02-02 18:18 UTC, AlexeyGvozdev commented on core/src/main/res/layout/add_button.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
иначе у тебя получается лишняя вложенность. А так у тебя лейаут будет просто добавлен в место вызова

2023-02-07 18:33 UTC, AlexeyGvozdev approved these changes

2023-02-07 18:34 UTC, merged