TASK-17 change icon bar
AlexeyGvozdev/TodoApp pull request #27
Opened 2023-01-29 16:29 UTC by kapkan1999

2023-01-30 19:18 UTC, chandrey34 commented on app/src/main/res/drawable/rectangle_19.xml
> +      android:fillColor="#C4C4C4"/>
цвета лучше выносить в colors, в модуле core храним

2023-01-30 19:18 UTC, chandrey34 commented on app/src/main/res/drawable/vector_1.xml
> +      android:strokeColor="#4B4B4B"
цвета лучше выносить в colors, в модуле core храним

2023-01-30 19:18 UTC, chandrey34 commented on app/src/main/res/drawable/vector_2.xml
> +      android:strokeColor="#A7A7A7"
цвета лучше выносить в colors, в модуле core храним

2023-01-30 19:23 UTC, chandrey34 commented on app/src/main/res/menu/bottom_view_add_but.xml
> +        android:id="@id/project_graph"
это не замечание, а уточнение: одинаковые id с List, так и задумывалось?

2023-02-01 15:29 UTC, AlexeyGvozdev requested changes

2023-02-05 15:39 UTC, Fail-Salikhov approved these changes

2023-02-05 18:59 UTC, AlexeyGvozdev requested changes

2023-02-05 18:59 UTC, AlexeyGvozdev commented on app/src/main/res/menu/bottom_view_add_but.xml
> +    <item
это удалить надо

2023-02-26 13:10 UTC, closed without merging