Task-42: Remove ActionBar
AlexeyGvozdev/TodoApp pull request #30
Opened 2023-01-31 10:02 UTC by DankanQ

2023-01-31 10:13 UTC, chandrey34 commented on core/src/main/res/values/colors.xml
> +    <color name="teal_700">#FF018786</color>
скажи, где ты используешь эти цвета и для чего?

2023-01-31 10:17 UTC, chandrey34 requested changes
есть уточнение

2023-01-31 10:24 UTC, DankanQ commented on core/src/main/res/values/colors.xml
> +    <color name="teal_700">#FF018786</color>
Подумал оставить, чтобы статус бар окрашивался. Удаляю?

2023-01-31 10:31 UTC, chandrey34 commented on core/src/main/res/values/colors.xml
> +    <color name="teal_700">#FF018786</color>
я не говорил, что это не правильно, я уточнил где ты их используешь, ведь если они там есть (а это стандартные цвета которые создает студия), значит ты их где-то должен использовать, в противном случае удалить.
Уточни у Алексея, какой цвет по дизайну использовать в статус баре,и оставь нужные тебе цвета, остальные, которые не юзаешь нигде - удали.

2023-01-31 10:54 UTC, AlexeyGvozdev requested changes

2023-01-31 10:54 UTC, AlexeyGvozdev commented on core/src/main/res/values-night/themes.xml
> +    <style name="Theme.Todo" parent="Theme.MaterialComponents.DayNight.NoActionBar">
Хочется узнать почему именно эта тема? Есть много разных тем NoActionBar. Хочется чтобы ты понял разницу

2023-01-31 10:54 UTC, AlexeyGvozdev commented on core/src/main/res/values/colors.xml
> +    <color name="teal_700">#FF018786</color>
цвет для статус бара оставляем и используем по назначению

2023-01-31 17:02 UTC, DankanQ commented on core/src/main/res/values-night/themes.xml
> +    <style name="Theme.Todo" parent="Theme.MaterialComponents.DayNight.NoActionBar">
Почему MaterialComponents

1) MaterialComponents расширяет виджеты из AppCompat, с помощью чего можно переписывать старые компоненты из AppCompat и брать новые свойства из MaterialComponents для изменения внешнего вида виджета.

2) Наследование темы позволяет явно не указывать путь к виджетам MaterialComponents , если они были расширены из AppCompat:

    `com.google.android.material.button.MaterialButton -> Button`

3) Также в MaterialComponents есть виджеты, которых нет в AppCompat, например FloatingActionButton. Можно взять FloatingActionButton из библиотеки Design:

    `compile 'com.android.support:design:23.1.1'`

    однако разве не лучше пользоваться одной библиотекой, которая предоставляет больший набор инструментов

Почему именно DayNight

Это более динамичный вариант. Можно создать единственный файл theme.xml и указать Theme.MaterialComponents.DayNight (в пулл реквесте у меня 2 таких файла - исправлю), либо же создать 2 файла themes.xml с Theme.MaterialComponents.Light для светлой темы и Theme.MaterialComponents для темной

2023-01-31 17:33 UTC, DankanQ commented on core/src/main/res/values/themes.xml
> +        <item name="android:forceDarkAllowed" tools:targetApi="q">false</item>
В Xiaomi у меня есть баг с отображением цветов в темной теме. Например если текст в макете темный, то MIUI 
его делает белым. Эта строчка все исправляет
https://stackoverflow.com/questions/62696305/theme-problem-when-dark-mode-is-activated-under-miui-11-12
https://stackoverflow.com/questions/60026842/how-do-i-force-apply-a-dark-theme-on-android

2023-02-05 09:13 UTC, chandrey34 approved these changes

2023-02-05 12:17 UTC, AlexeyGvozdev approved these changes

2023-02-05 15:37 UTC, Fail-Salikhov approved these changes

2023-02-05 17:20 UTC, merged