Task 10 : поправил верстку экрана задач
AlexeyGvozdev/TodoApp pull request #37
Opened 2023-02-08 18:04 UTC by chandrey34

* Поправил верстку экрана "Сегодня" список задач
* Применил стили, но оставил android:includeFontPadding="false" , т.к в стилях не применяется

2023-02-08 18:11 UTC, AlexeyGvozdev requested changes

2023-02-08 18:11 UTC, AlexeyGvozdev commented on task/src/main/res/layout/item_task_manager.xml
> +        android:layout_height="18dp"
верни как было

2023-02-08 18:11 UTC, AlexeyGvozdev commented on task/src/main/res/layout/item_task_manager.xml
> +        android:layout_marginTop="2dp"
этого не должно быть

2023-02-08 18:11 UTC, AlexeyGvozdev commented on task/src/main/res/layout/item_task_manager.xml
>          android:includeFontPadding="false"
надо разобраться почему в стилях не работает

2023-02-08 18:12 UTC, DankanQ approved these changes

2023-02-08 18:16 UTC, chandrey34 commented on task/src/main/res/layout/item_task_manager.xml
> +        android:layout_marginTop="2dp"
заменил на android:paddingTop="2dp"

2023-02-08 18:16 UTC, chandrey34 commented on task/src/main/res/layout/item_task_manager.xml
> +        android:layout_height="18dp"
если я верну как было, то невозможно сделать под дизайн и вся верстка тогда едет, отписался со скринами в тг

2023-02-08 21:26 UTC, chandrey34 commented on task/src/main/res/layout/item_task_manager.xml
>          android:includeFontPadding="false"
тут не могу понять почему, но если я удаляю с кода, то верстка едет

2023-02-08 21:27 UTC, chandrey34 commented on task/src/main/res/layout/item_task_manager.xml
> +        android:layout_marginTop="2dp"
заменил на paddingTop

2023-02-08 21:27 UTC, chandrey34 commented on task/src/main/res/layout/item_task_manager.xml
> +        android:layout_height="18dp"
вернул как было

2023-02-15 19:19 UTC, chandrey34 commented on task/src/main/res/layout/item_task_manager.xml
>          android:includeFontPadding="false"
заменил на style, будет в следующем пуше

2023-02-15 19:48 UTC, AlexeyGvozdev approved these changes

2023-02-15 19:48 UTC, AlexeyGvozdev commented on task/src/main/java/com/sinx/task/TaskListFragment.kt
> +                ContextCompat.getDrawable(requireContext(), com.sinx.core.R.drawable.divider)
сделай core_R

2023-02-15 20:03 UTC, chandrey34 commented on task/src/main/java/com/sinx/task/TaskListFragment.kt
> +                ContextCompat.getDrawable(requireContext(), com.sinx.core.R.drawable.divider)
готово

2023-02-15 20:19 UTC, merged