Task-12 добавил логику при нажати на чек-бокс
AlexeyGvozdev/TodoApp pull request #38
Opened 2023-02-10 13:31 UTC by Fail-Salikhov

2023-02-15 19:58 UTC, AlexeyGvozdev requested changes

2023-02-15 19:58 UTC, AlexeyGvozdev commented on buildSrc/src/main/kotlin/Dependency.kt
> +//    object Coroutine {
закомментированный код удаляем

2023-02-15 19:58 UTC, AlexeyGvozdev commented on task/build.gradle.kts
> +//    implementation(Dependency.Coroutine.coroutine)
удаляем

2023-02-15 19:58 UTC, AlexeyGvozdev commented on task/src/main/java/com/sinx/task/TaskListFragment.kt
> +            viewLifecycleOwner.repeatOnLifecycle(Lifecycle.State.STARTED) {
кажется что это дублирование строки выше, можно удалить

2023-02-15 19:58 UTC, AlexeyGvozdev commented on task/src/main/java/com/sinx/task/data/TaskRepositoryImpl.kt
> +        taskList = ArrayList(taskList)
ArrayList -> MutableList

2023-02-15 19:58 UTC, AlexeyGvozdev commented on task/src/main/java/com/sinx/task/data/TaskRepositoryImpl.kt
> +    override fun getListUseCase(): Flow<List<TaskItem>> {
Название функции не очень. лучше listTasksFlow. А зачем тут флоу? Нам же только при один раз нужно получить список. Проще просто вернуть список

2023-02-15 19:58 UTC, AlexeyGvozdev commented on task/src/main/java/com/sinx/task/model/GetListUseCase.kt
> +    operator fun invoke() = repository.getListUseCase()
название функций не очень надо поменять названия

2023-02-15 19:58 UTC, AlexeyGvozdev commented on task/src/main/java/com/sinx/task/model/TaskIsDoneUseCase.kt
> +    operator fun invoke(item: TaskItem) = repository.taskIsDoneUseCase(item)
названия

2023-02-15 19:58 UTC, AlexeyGvozdev commented on task/src/main/java/com/sinx/task/presentation/TaskViewModel.kt
> +    private val repository = TaskRepositoryImpl()
репозитории и юзкейсы давай в конструктор вынесем

2023-02-15 19:58 UTC, AlexeyGvozdev commented on task/src/main/java/com/sinx/task/presentation/TaskViewModel.kt
> +        Log.d("test", isChecked.toString())
логи удаляем

2023-02-15 19:58 UTC, AlexeyGvozdev commented on task/src/main/java/com/sinx/task/presentation/adapter/TaskItemViewHolder.kt
> +    fun bind (task: TaskItem) {
можно убрать лишний раз обращение к binding
и сделать так
```
fun bind(task: TaskItem) = with(binding) {
...
}
```

2023-02-15 19:58 UTC, AlexeyGvozdev commented on task/src/main/java/com/sinx/task/presentation/adapter/TaskItemViewHolder.kt
> +    fun bind (task: TaskItem) {
тут тоже через with надо сделать

2023-02-15 19:58 UTC, AlexeyGvozdev commented on task/src/main/java/com/sinx/task/presentation/adapter/TaskListAdapter.kt
> +        const val VIEW_TYPE_ENABLED = 0
в место констант можно использовать R.layout....

2023-02-15 20:01 UTC, AlexeyGvozdev requested changes

2023-02-15 20:01 UTC, AlexeyGvozdev commented on task/src/main/java/com/sinx/task/data/TaskRepositoryImpl.kt
> +    private val scope = CoroutineScope(Dispatchers.IO)
У репозитория не должно быть приватных полей. Этот класс только берёт откуда-то данные и передаёт тому кто попросил

2023-02-23 08:34 UTC, Fail-Salikhov commented on task/src/main/java/com/sinx/task/data/TaskRepositoryImpl.kt
> +    override fun getListUseCase(): Flow<List<TaskItem>> {
на тот случай что потом будет room, сразу сделал flow

2023-02-23 08:35 UTC, Fail-Salikhov commented on task/src/main/java/com/sinx/task/presentation/TaskViewModel.kt
> +    private val repository = TaskRepositoryImpl()
вынес

2023-02-23 08:35 UTC, Fail-Salikhov commented on task/src/main/java/com/sinx/task/presentation/TaskViewModel.kt
> +        Log.d("test", isChecked.toString())
удалил

2023-02-23 08:45 UTC, Fail-Salikhov commented on task/src/main/java/com/sinx/task/presentation/adapter/TaskListAdapter.kt
> +        const val VIEW_TYPE_ENABLED = 0
студия ругается "Const 'val' initializer should be a constant value"

2023-02-23 08:52 UTC, Fail-Salikhov commented on task/src/main/java/com/sinx/task/data/TaskRepositoryImpl.kt
> +    private val scope = CoroutineScope(Dispatchers.IO)
пока что репозиторий пока не берет данные и он сам их создает, а данные отдает через fun getListUseCase(): Flow<List<TaskItem>>
Приватные что бы из вне не могли изменить данные.

2023-02-23 08:52 UTC, Fail-Salikhov commented on task/src/main/java/com/sinx/task/presentation/adapter/TaskItemViewHolder.kt
> +    fun bind (task: TaskItem) {
ок

2023-02-23 08:59 UTC, Fail-Salikhov commented on task/src/main/java/com/sinx/task/model/GetListUseCase.kt
> +    operator fun invoke() = repository.getListUseCase()
поменял на GetTaskListUseCase

2023-02-23 08:59 UTC, Fail-Salikhov commented on task/src/main/java/com/sinx/task/model/TaskIsDoneUseCase.kt
> +    operator fun invoke(item: TaskItem) = repository.taskIsDoneUseCase(item)
поменял на TaskReadyUseCase 
?

2023-02-27 09:17 UTC, AlexeyGvozdev approved these changes

2023-02-27 11:13 UTC, merged