Task 29 not conflict
AlexeyGvozdev/TodoApp pull request #41
Opened 2023-02-24 21:52 UTC by Hercules0ff

2023-02-26 14:03 UTC, Hercules0ff commented
![Screenshot_20230226_170318](https://user-images.githubusercontent.com/116757778/221415274-a03539fa-874a-4dd7-976d-81363cfd83f9.png)

2023-03-05 12:16 UTC, AlexeyGvozdev requested changes

2023-03-05 12:16 UTC, AlexeyGvozdev commented on project/build.gradle.kts
> +    implementation("androidx.navigation:navigation-common-ktx:2.4.1")
Это зачем? если нужно, то сделай как остальные

2023-03-05 12:16 UTC, AlexeyGvozdev commented on app/src/main/res/drawable/rectangle_19.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
этот файл надо удалить

2023-03-05 12:16 UTC, AlexeyGvozdev commented on app/src/main/res/drawable/vector_1.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
сделай нормальное название файла

2023-03-05 12:16 UTC, AlexeyGvozdev commented on app/src/main/res/drawable/vector_2.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
поменяй название

2023-03-05 12:16 UTC, AlexeyGvozdev commented on app/src/main/res/layout/activity_main.xml
> +    tools:theme = "@style/Theme.Todo"
верни как было

2023-03-05 12:16 UTC, AlexeyGvozdev commented on app/src/main/res/menu/bottom_view_add_but.xml
> +<?xml version="1.0" encoding="utf-8"?>
а этот файл зачем?

2023-03-05 12:16 UTC, AlexeyGvozdev commented on app/src/main/res/values/colors.xml
> +    <color name="vector_1_fill">#00000000</color>
цвета мы заносим в core модуль и лучше переиспользовать оттуда цвета

2023-03-14 18:03 UTC, AlexeyGvozdev requested changes

2023-03-14 18:03 UTC, AlexeyGvozdev commented on app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintHorizontal_bias="0.0"
это зачем?

2023-03-14 18:03 UTC, AlexeyGvozdev commented on app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintVertical_bias="0.0"
а это зачем?

2023-03-14 18:03 UTC, AlexeyGvozdev commented on app/src/main/res/layout/activity_main.xml
> +        app:menu="@menu/bottom_menu" />
лишний пробел?

2023-03-14 18:03 UTC, AlexeyGvozdev commented on app/src/main/res/menu/bottom_menu.xml
> +        android:title="" />
а нельзя title не указывать?

2023-03-29 21:49 UTC, chandrey34 commented on app/src/main/res/drawable/project_icon.xml
> +</vector>
если это иконка, то не правильно, качаем иконку с фигмы в формате svg, и добавляем в папку drawable через - правая кнопка мыши - vector asset

2023-03-29 21:50 UTC, chandrey34 commented on app/src/main/res/drawable/task_icon.xml
> +</vector>
если это иконка, то не правильно, качаем иконку с фигмы в формате svg, и добавляем в папку drawable через - правая кнопка мыши - vector asset

2023-03-29 22:04 UTC, chandrey34 commented on core/src/main/res/values/colors.xml
> +    <color name="task_icon_stroke">#4B4B4B</color>
такой цвет уже есть, не стоит дублировать, переиспользуй уже определенный цвет

2023-03-29 22:05 UTC, chandrey34 commented on core/src/main/res/values/colors.xml
> +    <color name="project_icon_stroke">#A7A7A7</color>
такой цвет уже есть, не стоит дублировать, переиспользуй уже определенный цвет

2023-03-29 22:23 UTC, chandrey34 commented on core/src/main/res/values/colors.xml
> +    <color name="task_icon_stroke">#4B4B4B</color>
такой цвет уже есть, не стоит дублировать, удали и если нужно переиспользуй уже определенный цвет

2023-03-29 22:26 UTC, chandrey34 requested changes
есть вопросы и замечания

2023-03-30 18:31 UTC, chandrey34 commented on app/src/main/res/drawable/project_icon.xml
> +      android:fillColor="@color/task_and_project_icon_fill"
подскажи пожалуйста, для чего это используем? может я не до понял, но я в коде убрал, запустил и изменений не нашел

2023-04-02 20:26 UTC, AlexeyGvozdev requested changes

2023-04-02 20:26 UTC, AlexeyGvozdev commented on task/src/main/java/com/sinx/task/data/TaskRepositoryImpl.kt
> +import com.sinx.task.model.TaskRepository
А как этот файл тут оказался?

2023-04-02 20:26 UTC, AlexeyGvozdev commented on task/src/main/java/com/sinx/task/model/GetTaskListUseCase.kt
> +package com.sinx.task.model
Это не твои изменения

2023-04-02 20:26 UTC, AlexeyGvozdev commented on task/src/main/java/com/sinx/task/model/TaskReadyUseCaseImpl.kt
> +package com.sinx.task.model
И это тоже не твоё

2023-04-02 20:26 UTC, AlexeyGvozdev commented on task/src/main/java/com/sinx/task/model/TaskRepository.kt
> +package com.sinx.task.model
и это

2023-04-02 20:26 UTC, AlexeyGvozdev commented on task/src/main/java/com/sinx/task/presentation/adapter/TaskItemDiffCallback.kt
> +package com.sinx.task.presentation.adapter
и это

2023-04-02 20:26 UTC, AlexeyGvozdev commented on task/src/main/java/com/sinx/task/presentation/adapter/TaskItemViewHolder.kt
> +package com.sinx.task.presentation.adapter
и это

2023-04-02 20:26 UTC, AlexeyGvozdev commented on task/src/main/java/com/sinx/task/presentation/adapter/TaskListAdapter.kt
> +package com.sinx.task.presentation.adapter
и это

2023-04-05 18:31 UTC, closed without merging