Task 61 task list in new module
AlexeyGvozdev/TodoApp pull request #42
Opened 2023-03-03 11:35 UTC by Fail-Salikhov

создал новый модуль: taskList. В нем находится адаптер, декоратор, xml и логика

2023-03-05 12:18 UTC, AlexeyGvozdev requested changes

2023-03-05 12:18 UTC, AlexeyGvozdev commented on task/src/main/java/com/sinx/task/TaskListFragment.kt
>              override fun onMoreItemClickListener(item: TaskItem) {
давай удалим этот листенер, его никто не использует

2023-03-05 12:18 UTC, AlexeyGvozdev commented on taskList/src/main/java/com/sinx/taskList/TaskItem.kt
>      val id: Int = UNDEFINED_ID,
скажи, а нам в адаптере нужен будет id? кажется, можно удалить

2023-03-05 13:49 UTC, Fail-Salikhov commented on task/src/main/java/com/sinx/task/TaskListFragment.kt
>              override fun onMoreItemClickListener(item: TaskItem) {
пока не используем, удалю

2023-03-05 13:50 UTC, Fail-Salikhov commented on taskList/src/main/java/com/sinx/taskList/TaskItem.kt
>      val id: Int = UNDEFINED_ID,
в адаптере не нужен сейчас. удаляю

2023-03-12 10:07 UTC, AlexeyGvozdev approved these changes

2023-03-12 10:07 UTC, merged