Task 63 test for vm list task
AlexeyGvozdev/TodoApp pull request #43
Opened 2023-03-12 14:19 UTC by Fail-Salikhov

2023-03-14 18:02 UTC, AlexeyGvozdev requested changes

2023-03-14 18:02 UTC, AlexeyGvozdev commented on task/src/test/java/com/sinx/task/presentation/TaskViewModelTest.kt
> +        val scope = CoroutineScope(Dispatchers.Unconfined)
Это что за диспатчер? Почему именно такой?

2023-03-14 18:02 UTC, AlexeyGvozdev commented on task/src/test/java/com/sinx/task/presentation/TaskViewModelTest.kt
> +class MainDispatcherRule(
я думаю эту штуку можно в кор вынести, так как её мы будем переиспользовать

2023-03-14 18:02 UTC, AlexeyGvozdev commented on task/src/test/java/com/sinx/task/presentation/TaskViewModelTest.kt
> +}
давай сделаем ещё два теста. если ошибка в одном или в другом методе репозитория

2023-03-15 08:19 UTC, Fail-Salikhov commented on task/src/main/java/com/sinx/task/TaskListFragment.kt
> +        ViewModelProvider(this, TaskViewModelFactory())[TaskViewModel::class.java]
сделал

2023-03-15 08:21 UTC, Fail-Salikhov commented on task/src/test/java/com/sinx/task/presentation/TaskViewModelTest.kt
> +//        begin
ok

2023-03-15 09:15 UTC, Fail-Salikhov commented on task/src/test/java/com/sinx/task/presentation/TaskViewModelTest.kt
> +        val scope = CoroutineScope(Dispatchers.Unconfined)
https://developer.android.com/kotlin/coroutines/test - в документации Unconfined тоже использовался.
Заменил на Main

2023-04-03 17:21 UTC, AlexeyGvozdev requested changes

2023-04-03 17:21 UTC, AlexeyGvozdev commented on task/src/test/java/com/sinx/task/presentation/TaskViewModelTest.kt
> +                    throw Exception()
IlligalStateException("some string")

2023-04-04 17:08 UTC, AlexeyGvozdev approved these changes

2023-04-04 17:39 UTC, merged