Task 57 add project logic
AlexeyGvozdev/TodoApp pull request #44
Opened 2023-03-12 19:50 UTC by chandrey34

2023-03-12 19:52 UTC, chandrey34 commented on project/src/main/java/com/sinx/project/data/ProjectRepositoryImpl.kt
> +internal class ProjectRepositoryImpl : ProjectRepository {
internal убрал

2023-03-12 20:11 UTC, Fail-Salikhov approved these changes

2023-03-13 09:18 UTC, Fail-Salikhov approved these changes

2023-03-13 09:18 UTC, Fail-Salikhov commented on project/src/main/java/com/sinx/project/presentation/ProjectViewModel.kt
> +        viewModelScope.launch {
в task-63  у себя сделал рефактор убрал блок инит глянь как сделал

2023-03-13 09:18 UTC, Fail-Salikhov commented on project/src/main/java/com/sinx/project/ProjectFragment.kt
> +
в таск 63 ушел от лейтинит

2023-03-13 18:40 UTC, chandrey34 commented on project/src/main/java/com/sinx/project/presentation/ProjectViewModel.kt
> +        viewModelScope.launch {
ок, готово

2023-03-13 18:40 UTC, chandrey34 commented on project/src/main/java/com/sinx/project/ProjectFragment.kt
> +
ок, готово

2023-03-14 17:56 UTC, AlexeyGvozdev requested changes

2023-03-14 17:56 UTC, AlexeyGvozdev commented on project/src/main/java/com/sinx/project/Constans.kt
> +    const val REQUEST_KEY = "requestKey"
у нас много будет шторок, давай более конкретные названия переменных сделаем

2023-03-14 17:56 UTC, AlexeyGvozdev commented on project/src/main/java/com/sinx/project/ProjectFragment.kt
> +    private val viewModel by lazy {
почему нельзя через просто by viewmodels()?

2023-03-14 17:56 UTC, AlexeyGvozdev commented on project/src/main/java/com/sinx/project/ProjectFragment.kt
> +                binding.rvProjectList.adapter = ProjectListAdapter(it)
давайте список один раз проинициализируем и будет просто notify делать

2023-03-14 17:56 UTC, AlexeyGvozdev commented on project/src/main/java/com/sinx/project/ProjectFragment.kt
>                  .build()
название диплинка корректное?

2023-03-14 17:56 UTC, AlexeyGvozdev commented on project/src/main/java/com/sinx/project/ProjectFragment.kt
>                  .build()
почему фрагмент решает, что надо навигироваться?

2023-03-14 17:56 UTC, AlexeyGvozdev commented on project/src/main/java/com/sinx/project/data/ProjectListModel.kt
> +data class ProjectListModel(val nameProject: String, val dataProject: String)
почему удалил интернал?

2023-03-14 17:56 UTC, AlexeyGvozdev commented on project/src/main/java/com/sinx/project/ProjectFragment.kt
> +    private val viewModel by lazy {
и в аргументы viewModels() передать фактори

2023-03-14 21:21 UTC, chandrey34 commented on project/src/main/java/com/sinx/project/data/ProjectListModel.kt
> +data class ProjectListModel(val nameProject: String, val dataProject: String)
вернул обратно, так же добавил к юзкейсам, репозиторию и вьюмодель, если правильно понимаю таким образом мы делаем их видимыми в границах модуля

2023-03-14 21:21 UTC, chandrey34 commented on project/src/main/java/com/sinx/project/ProjectFragment.kt
> +    private val viewModel by lazy {
готово

2023-03-14 21:27 UTC, chandrey34 commented on project/src/main/java/com/sinx/project/Constans.kt
> +    const val REQUEST_KEY = "requestKey"
готово

2023-03-15 21:05 UTC, chandrey34 commented on project/src/main/java/com/sinx/project/ProjectFragment.kt
>                  .build()
если правильно понял, то готово. в этой задаче на этот участок кода не обращал внимания, он делался в предыдущей)

2023-03-17 17:47 UTC, chandrey34 commented on project/src/main/java/com/sinx/project/ProjectFragment.kt
> +                binding.rvProjectList.adapter = ProjectListAdapter(it)
готово

2023-04-02 20:33 UTC, AlexeyGvozdev requested changes

2023-04-02 20:33 UTC, AlexeyGvozdev commented on project/src/main/java/com/sinx/project/ProjectFragment.kt
> +            val newProject = ProjectListModel(result.toString(), "12.03.2023")
а зачем тут так дату передавать? Давай во вьюмодели будем дату вычислять

2023-04-02 20:33 UTC, AlexeyGvozdev commented on project/src/main/java/com/sinx/project/presentation/ProjectViewModel.kt
> +        val requestBottomSheetAddProjectFragment = NavDeepLinkRequest.Builder
нет, не правильно так делать. Надо через flow говорить фрагменту, чтобы он навигировался

2023-04-11 20:40 UTC, chandrey34 commented on project/src/main/java/com/sinx/project/ProjectFragment.kt
> +            val newProject = ProjectListModel(result.toString(), "12.03.2023")
ок

2023-04-11 20:41 UTC, chandrey34 commented on project/src/main/java/com/sinx/project/presentation/ProjectViewModel.kt
> +        val requestBottomSheetAddProjectFragment = NavDeepLinkRequest.Builder
ок

2023-04-24 17:46 UTC, AlexeyGvozdev requested changes

2023-04-24 17:46 UTC, AlexeyGvozdev commented on project/src/main/java/com/sinx/project/presentation/ProjectViewModel.kt
> +        replay = 1,
replay = 0

2023-04-25 06:42 UTC, AlexeyGvozdev approved these changes

2023-04-25 06:43 UTC, merged