TASK-23-repeat bottom sheet
AlexeyGvozdev/TodoApp pull request #46
Opened 2023-04-03 20:32 UTC by Hercules0ff

2023-04-04 07:38 UTC, chandrey34 commented on task/src/main/java/com/sinx/task/BottomSheetRepeatFragment.kt
> +
пустая строка, кажется детект как раз на это и поругался

2023-04-04 07:41 UTC, chandrey34 commented on task/src/main/res/layout/bottom_sheet_repeat.xml
> +        android:id="@+id/imageView2"
давай будем давать более корректные названия?)

2023-04-04 07:44 UTC, chandrey34 requested changes
есть замечания, чуть позже гляну еще более детально

2023-04-04 16:35 UTC, Fail-Salikhov commented on task/src/main/res/layout/bottom_sheet_repeat.xml
> +        android:layout_width="wrap_content"
потом эта  кнопка не понадобиться? мб сразу дать id

2023-04-05 17:02 UTC, chandrey34 approved these changes

2023-04-05 20:11 UTC, chandrey34 approved these changes

2023-04-10 19:03 UTC, chandrey34 approved these changes

2023-04-11 16:37 UTC, Fail-Salikhov approved these changes

2023-04-11 21:10 UTC, chandrey34 commented on task/src/main/res/layout/bottom_sheet_repeat.xml
> +        <androidx.appcompat.widget.AppCompatCheckBox
примени стили, чтобы определялся шрифт и размер шрифта в соответствии с дизайном, к каждому не буду писать, но понятно что это нужно сделать для всех дней недели

2023-04-11 21:11 UTC, chandrey34 requested changes
есть не значительные замечания по верстке

2023-04-11 21:12 UTC, chandrey34 commented on task/src/main/res/layout/bottom_sheet_repeat.xml
> +        <com.google.android.material.chip.Chip
примени стили к каждой чипсе

2023-04-24 18:14 UTC, AlexeyGvozdev requested changes

2023-04-24 18:14 UTC, AlexeyGvozdev commented on task/src/main/java/com/sinx/task/BottomSheetRepeatFragment.kt
> +                    linearLayout.visibility = View.VISIBLE
isInvisible

2023-04-24 18:14 UTC, AlexeyGvozdev commented on task/src/main/res/layout/bottom_sheet_repeat.xml
> +        <androidx.appcompat.widget.AppCompatCheckBox
Согласен с Андреем

2023-04-24 18:14 UTC, AlexeyGvozdev commented on task/src/main/res/layout/bottom_sheet_repeat.xml
> +        android:layout_width="wrap_content"
Создай стиль для кнопки Ok

2023-04-25 06:47 UTC, AlexeyGvozdev commented
Давай дизайнеру покажем что получилось

2023-05-21 08:03 UTC, AlexeyGvozdev requested changes

2023-06-06 15:06 UTC, chandrey34 approved these changes

2023-06-06 15:09 UTC, merged