empty task list design with logic created
AlexeyGvozdev/TodoApp pull request #49
Opened 2023-04-24 21:29 UTC by Hercules0ff

2023-04-25 06:46 UTC, AlexeyGvozdev approved these changes

2023-04-25 06:49 UTC, AlexeyGvozdev requested changes
Давай покажем дизайнеру что получилось

2023-05-02 12:21 UTC, chandrey34 commented on task/src/main/res/layout/task_list_layout.xml
> +    <TextView
давай применим сюда стиль согласно дизайну? style=

2023-05-02 12:22 UTC, chandrey34 requested changes
есть небольшое замечание + нужно посмотреть совпадает ли с макетом дизайна

2023-05-11 16:06 UTC, Fail-Salikhov approved these changes

2023-05-22 08:22 UTC, AlexeyGvozdev approved these changes

2023-05-22 08:30 UTC, chandrey34 approved these changes

2023-05-29 17:42 UTC, merged