Add recyclerview for project list
AlexeyGvozdev/TodoApp pull request #5
Opened 2023-01-19 22:20 UTC by chandrey34

* Верстка экрана "Список проектов"
* Ресайклер проектов

2023-01-22 16:12 UTC, Fail-Salikhov approved these changes

2023-01-22 18:22 UTC, AlexeyGvozdev requested changes

2023-01-22 18:22 UTC, AlexeyGvozdev commented on app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintHorizontal_bias="0.0"
биас зачем?

2023-01-22 18:22 UTC, AlexeyGvozdev commented on project/src/main/java/com/sinx/project/ProjectFragment.kt
> +        val recyclerView = view.findViewById(R.id.rvProjectList) as RecyclerView
так ты же вьюбиндинг подключил. Давай его использовать

2023-01-22 18:22 UTC, AlexeyGvozdev commented on project/src/main/java/com/sinx/project/adapter/ProjectListAdapter.kt
> +class ProjectListAdapter(private val projectListModels: ArrayList<ProjectListModel>) : RecyclerView.Adapter<ProjectListAdapter.ProjectListViewHolder>() {
internal добавь

2023-01-22 18:22 UTC, AlexeyGvozdev commented on project/src/main/java/com/sinx/project/adapter/ProjectListAdapter.kt
> +    class ProjectListViewHolder(item: View) : RecyclerView.ViewHolder(item) {
давай биндинг передавать в конструктор

2023-01-22 18:22 UTC, AlexeyGvozdev commented on project/src/main/java/com/sinx/project/adapter/ProjectListAdapter.kt
> +            binding.movingProject.setImageResource(com.sinx.core.R.drawable.moving)
так как у тебя два класса R которые ты используешь, то можно в импорте сделать вот так 
import com.sinx.core.R as core_R
и тут использовать core_R.drawable.moving

2023-01-22 18:22 UTC, AlexeyGvozdev commented on project/src/main/java/com/sinx/project/adapter/ProjectListAdapter.kt
> +    override fun getItemCount(): Int {
тут можно в одну строку сделать override fun getItemCount() = projectListModels.size

2023-01-22 18:22 UTC, AlexeyGvozdev commented on project/src/main/res/font/project_data.xml
> +<font-family xmlns:app="http://schemas.android.com/apk/res-auto"
в кор давай вынесем. Так как это надо всем

2023-01-22 18:22 UTC, AlexeyGvozdev commented on project/src/main/res/layout/list_project.xml
> +    android:layout_marginLeft="32dp"
horizontal_margin = 32.dp

2023-01-22 18:22 UTC, AlexeyGvozdev commented on project/src/main/res/layout/list_project.xml
> +    android:layout_marginLeft="32dp"
это вместо left и right

2023-01-22 18:22 UTC, AlexeyGvozdev commented on project/src/main/res/layout/list_project.xml
> +            android:text="17.01.2023"
текст лучше через tools:text делать. Так не будет видно в приложении, но видно в студии

2023-01-22 18:22 UTC, AlexeyGvozdev commented on project/src/main/res/layout/project_layout.xml
> +    <RelativeLayout
RelativeLayout деперекейтед. Поменяй на constraint

2023-01-22 18:22 UTC, AlexeyGvozdev commented on project/src/main/res/layout/project_layout.xml
> +            android:text="@string/titleProject"
tools:text

2023-01-22 18:22 UTC, AlexeyGvozdev commented on project/src/main/res/values/colors.xml
> +    <color name="project_title">#4B4B4B</color>
у тебя другие цвета хорошо названы. Переименуй эти три и вынеси в кор модуль

2023-01-22 18:22 UTC, AlexeyGvozdev commented on project/src/main/res/values/themes.xml
> +    <style name="Theme.Todo" parent="Theme.MaterialComponents.DayNight.DarkActionBar">
это зачем?

2023-01-22 18:47 UTC, chandrey34 commented on app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintHorizontal_bias="0.0"
я в activity_main в принципе ничего не трогал, не знаю почему добавились сюда, убрал bias

2023-01-22 18:48 UTC, chandrey34 commented on app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintVertical_bias="1.0"
этот тоже убрал

2023-01-22 19:30 UTC, chandrey34 commented on project/src/main/java/com/sinx/project/ProjectFragment.kt
> +        val recyclerView = view.findViewById(R.id.rvProjectList) as RecyclerView
готово

2023-01-22 19:34 UTC, chandrey34 commented on project/src/main/java/com/sinx/project/adapter/ProjectListAdapter.kt
> +class ProjectListAdapter(private val projectListModels: ArrayList<ProjectListModel>) : RecyclerView.Adapter<ProjectListAdapter.ProjectListViewHolder>() {
готово

2023-01-22 19:34 UTC, chandrey34 commented on project/src/main/java/com/sinx/project/adapter/ProjectListAdapter.kt
> +    class ProjectListViewHolder(item: View) : RecyclerView.ViewHolder(item) {
готово

2023-01-22 19:36 UTC, chandrey34 commented on project/src/main/java/com/sinx/project/adapter/ProjectListAdapter.kt
> +            binding.movingProject.setImageResource(com.sinx.core.R.drawable.moving)
ок, готово

2023-01-22 19:37 UTC, chandrey34 commented on project/src/main/java/com/sinx/project/adapter/ProjectListAdapter.kt
> +    override fun getItemCount(): Int {
готово

2023-01-22 19:42 UTC, chandrey34 commented on project/src/main/res/font/project_data.xml
> +<font-family xmlns:app="http://schemas.android.com/apk/res-auto"
вынес всю папку font в core

2023-01-22 19:47 UTC, chandrey34 commented on project/src/main/res/layout/list_project.xml
> +    android:layout_marginLeft="32dp"
готово

2023-01-22 19:53 UTC, chandrey34 commented on project/src/main/res/layout/list_project.xml
> +            android:text="17.01.2023"
готово

2023-01-22 19:54 UTC, chandrey34 commented on project/src/main/res/layout/project_layout.xml
> +    <RelativeLayout
готово

2023-01-22 19:55 UTC, chandrey34 commented on project/src/main/res/layout/project_layout.xml
> +            android:text="@string/titleProject"
а тут зачем tools:text ? мы же явно указываем, какой текст хотим видеть, он тут не будет меняться

2023-01-22 19:57 UTC, chandrey34 commented on project/src/main/res/values/themes.xml
> +    <style name="Theme.Todo" parent="Theme.MaterialComponents.DayNight.DarkActionBar">
студия сама это создала, даже не знаю что это, удалил

2023-01-22 20:10 UTC, chandrey34 commented on project/src/main/res/values/colors.xml
> +    <color name="project_title">#4B4B4B</color>
они хорошо названы, потому что называл их не я, были уже. 
названия поменял, в core вынес, так же удалил не использующиеся в проекте цвета

2023-01-23 10:41 UTC, NatalyTsivileva commented on project/src/main/java/com/sinx/project/adapter/ProjectListAdapter.kt
> +            binding.movingProject.setImageResource(com.sinx.core.R.drawable.moving)
> AlexeyGvozdev

ого. не знала такого)

2023-01-23 11:01 UTC, NatalyTsivileva reviewed
Небольшие замечания) в целом хорошо

2023-01-23 11:02 UTC, NatalyTsivileva approved these changes

2023-01-23 11:05 UTC, NatalyTsivileva requested changes
Небольшие замечания) в целом хорошо

2023-01-23 14:24 UTC, AlexeyGvozdev commented on project/src/main/res/layout/project_layout.xml
> +            android:text="@string/titleProject"
ага, оставь

2023-01-23 14:30 UTC, AlexeyGvozdev requested changes

2023-01-23 18:30 UTC, chandrey34 commented on project/src/main/java/com/sinx/project/ProjectFragment.kt
> +    private fun dataListProject(): ArrayList<ProjectListModel> {
ок, спасибо за разъяснение)

2023-01-23 18:30 UTC, chandrey34 commented on project/src/main/java/com/sinx/project/adapter/ProjectListAdapter.kt
> +internal class ProjectListAdapter(private val projectListModels: ArrayList<ProjectListModel>) : RecyclerView.Adapter<ProjectListAdapter.ProjectListViewHolder>() {
Ок, спасибо, поправил

2023-01-23 18:50 UTC, chandrey34 commented on project/src/main/java/com/sinx/project/data/ProjectListModel.kt
> +data class ProjectListModel(val nameProject: String, val dataProject: String)
готово

2023-01-23 18:51 UTC, chandrey34 commented on project/src/main/res/layout/list_project.xml
> +        <ImageView
готово

2023-01-23 19:41 UTC, chandrey34 commented on project/build.gradle
> +    implementation project(path: ':core')
с твоей помощью готово

2023-01-24 05:35 UTC, NatalyTsivileva approved these changes

2023-01-24 21:21 UTC, AlexeyGvozdev approved these changes

2023-01-24 21:32 UTC, merged