Task 65 add dagger
AlexeyGvozdev/TodoApp pull request #51
Opened 2023-05-22 09:07 UTC by simt11

Внедрена реализация зависимостей через dagger, от DbModule до TaskListFragment

2023-05-22 18:25 UTC, AlexeyGvozdev requested changes

2023-05-22 18:25 UTC, AlexeyGvozdev commented on task/src/main/java/com/sinx/task/presentation/TaskAdapter.kt
> +annotation class Feature
все скоупы туда отправляем

2023-05-22 18:26 UTC, AlexeyGvozdev requested changes

2023-05-22 18:26 UTC, AlexeyGvozdev commented on coreDB/src/main/java/com/sinx/coreDB/di/DbModule.kt
> -    }
Нет скоупа

2023-05-22 18:26 UTC, AlexeyGvozdev commented on coreDB/src/main/java/com/sinx/coreDB/di/DbModule.kt
> +    @Provides
Тут тоже

2023-05-22 18:26 UTC, AlexeyGvozdev commented
Зачем нужны скоупы?

2023-05-23 07:38 UTC, simt11 commented on app/src/main/java/com/sinx/todo/App.kt
> -    private val dbModule = DbModule()
Сделано

2023-05-23 10:57 UTC, simt11 commented on task/src/main/java/com/sinx/task/TaskListFragment.kt
> +    internal lateinit var taskViewModelFactory: Lazy<TaskViewModel.Factory>
Добавил в коммент

2023-05-23 11:54 UTC, simt11 commented on task/src/main/java/com/sinx/task/presentation/TaskAdapter.kt
> +annotation class Feature
Сделано

2023-05-23 13:35 UTC, simt11 commented on coreDB/src/main/java/com/sinx/coreDB/di/DbModule.kt
> -    }
При вынесеении Scope в core, они уже не подтягиваются. Словно нет зависимостей

2023-05-23 13:37 UTC, simt11 commented on coreDB/src/main/java/com/sinx/coreDB/di/DbModule.kt
> -    }
При переносе скоупов в кор, они подтягиваются но вызывают ошибку
AppComponent.java:7: error: cannot find symbol
@AppScope()
^
symbol: class AppScope

Пока не разобрался в чем дело

2023-05-24 11:01 UTC, simt11 commented on task/src/main/java/com/sinx/task/TaskListFragment.kt
> +    @Inject
Первое предположение - да,  можно. Если инжектить в конструктор. Но инжект происходит в onAttach. А в конструкторе определяется раньше него. Это не сработает.
  В итоге на данный момент я не знаю, можно ли без @Inject lateinit var

2023-05-26 16:47 UTC, simt11 commented on task/src/main/java/com/sinx/task/presentation/TaskViewModel.kt
> +class TaskViewModel(taskDAO: TaskDAO) : ViewModel() {
viewModel снова получает UseCase - тесты проходит

2023-05-26 16:48 UTC, simt11 commented on coreDB/src/main/java/com/sinx/coreDB/di/DbModule.kt
> +    @Provides
Добавил скоупы

2023-05-26 17:25 UTC, simt11 commented on task/src/main/java/com/sinx/task/TaskListFragment.kt
> +    internal lateinit var taskViewModelFactory: Lazy<TaskViewModel.Factory>
/*используется для отложенной инициализации taskViewModelFactory.

Lazy - это интерфейс, который позволяет отложить вычисление значения до момента его первого доступа.
При первом доступе, Lazy выполняет вычисление и запоминает результат,
а затем возвращает его для последующих запросов.

Когда происходит доступ к taskViewModelFactory, он будет инициализирован с использованием
соответствующего Factory класса для TaskViewModel.

Использование Lazy позволяет оптимизировать ресурсы и избежать
ненужной инициализации taskViewModelFactory, если он не используется в коде.
Вычисление значения происходит только при фактическом обращении к taskViewModelFactory,
а не при создании объекта, в котором он объявлен.
Resolv`ит компоненты и сохраняет их внутри. Отложенная.
Другой вариант  Provider<> позволяет каждый раз при обращении к нему получать снова и снова.
Полезно если хотим получать каждый раз новый инстанс. Полезно в фабриках
*/

2023-05-26 17:53 UTC, simt11 commented on task/src/main/java/com/sinx/task/TaskListFragment.kt
> +    internal lateinit var taskViewModelFactory: Lazy<TaskViewModel.Factory>
используется для отложенной инициализации taskViewModelFactory.
Lazy - это интерфейс, который позволяет отложить вычисление значения до момента его первого доступа.
При первом доступе, Lazy выполняет вычисление и запоминает результат,
а затем возвращает его для последующих запросов.

Когда происходит доступ к taskViewModelFactory, он будет инициализирован с использованием
соответствующего Factory класса для TaskViewModel.

Использование Lazy позволяет оптимизировать ресурсы и избежать
ненужной инициализации taskViewModelFactory, если он не используется в коде.
Вычисление значения происходит только при фактическом обращении к taskViewModelFactory,
а не при создании объекта, в котором он объявлен.
Resolv`ит компоненты и сохраняет их внутри. Отложенная.
Другой вариант Provider<> позволяет каждый раз при обращении к нему получать снова и снова.
Полезно если хотим получать каждый раз новый инстанс. Полезно в фабриках

2023-05-26 17:54 UTC, simt11 commented on coreDB/src/main/java/com/sinx/coreDB/di/DbModule.kt
> +        return provideToDoAppDatabase(context).taskDao()
Сделано

2023-05-26 18:01 UTC, simt11 commented on task/src/main/java/com/sinx/task/presentation/TaskAdapter.kt
> +    @get:RestrictTo(RestrictTo.Scope.LIBRARY)
переименовал TaskAdapter -> TaskComponent

2023-05-30 13:34 UTC, AlexeyGvozdev commented on coreDB/src/main/java/com/sinx/coreDB/di/DbModule.kt
> +    fun provideToDoAppDatabase(context: Context) = ToDoAppDatabase.getInstance(context)
Лучше явно прописывать что возвращает метод

2023-05-30 13:36 UTC, AlexeyGvozdev commented on task/src/main/java/com/sinx/task/presentation/TaskViewModel.kt
> +/*
это надо удалить

2023-05-30 13:37 UTC, AlexeyGvozdev commented on task/src/main/java/com/sinx/task/TaskListFragment.kt
> +    override fun onAttach(context: Context) {
этот метод надо удалить

2023-05-30 13:52 UTC, simt11 commented on task/src/main/java/com/sinx/task/presentation/TaskViewModel.kt
> +/*
сделано

2023-05-30 13:52 UTC, simt11 commented on task/src/main/java/com/sinx/task/TaskListFragment.kt
> +    override fun onAttach(context: Context) {
сделано

2023-05-31 15:08 UTC, closed without merging