Task 22 priority sheet
AlexeyGvozdev/TodoApp pull request #58
Opened 2023-06-19 09:57 UTC by simt11

Добавлена нижняя шторка, для выбора приоритета задачи.

![ezgif com-resize](https://github.com/AlexeyGvozdev/TodoApp/assets/25998931/c5de44db-59af-48db-96f5-c18c4bc5215e)

2023-06-19 15:08 UTC, chandrey34 commented on task/src/main/res/layout/bottom_sheet_priority_layout.xml
> +        style="@style/TextAppearance.AppCompat"
тут тот же вопрос, ну и ниже аналогично

2023-06-19 15:28 UTC, chandrey34 commented on task/src/main/java/com/sinx/task/BottomSheetPrioritySheetFragment.kt
> +class BottomSheetPrioritySheetFragment :
Кажется много sheet в названии)

2023-06-19 15:39 UTC, chandrey34 commented on task/src/main/java/com/sinx/task/presentation/PrioritySheetViewModel.kt
> +class PrioritySheetViewModel : ViewModel() {
а почему это не в TaskViewModel сделать?

2023-06-21 09:17 UTC, simt11 commented on task/src/main/res/layout/bottom_sheet_priority_layout.xml
> +        style="@style/TextAppearance.AppCompat"
Поменял на "@style/Body2", @+id/priority_text - здесь текст жирный, по дизайну такого не должно быть

2023-06-21 09:18 UTC, simt11 commented on task/src/main/res/layout/bottom_sheet_priority_layout.xml
> +        style="@style/TextAppearance.AppCompat"
Поменял на "@style/Body2", @+id/priority_text - здесь текст жирный, по дизайну такого не должно быть. Либо не хватает стиля

2023-06-21 09:20 UTC, simt11 commented on task/src/main/java/com/sinx/task/BottomSheetPrioritySheetFragment.kt
> +class BottomSheetPrioritySheetFragment :
изменил на BottomSheetPriorityFragment

2023-06-21 09:27 UTC, simt11 commented on task/src/main/java/com/sinx/task/presentation/PrioritySheetViewModel.kt
> +class PrioritySheetViewModel : ViewModel() {
Этим, я сохраняю пары Фрагмент-ВьюМодель
AddTaskFragment - PrioritySheetViewModel
TaskListFragment - TaskViewModel

Чтобы не было, разделять по напрвлениям, сохранять смысловую привязку и читаемость

2023-06-21 09:38 UTC, simt11 commented on app/src/main/res/navigation/task_graph.xml
> +            android:id="@+id/deepLink2"
Поправлено

2023-06-21 09:40 UTC, simt11 commented on task/src/main/java/com/sinx/task/presentation/PrioritySheetViewModel.kt
> +            .fromUri("app://task.BottomSheetPrioritySheetFragment".toUri())
Не понятно, что ты имеешь ввиду. Можешь переформулировать вопрос или добавить подробностей.

2023-06-21 21:31 UTC, chandrey34 commented on task/src/main/res/layout/bottom_sheet_priority_layout.xml
> +        style="@style/TextAppearance.AppCompat"
не, я имел ввиду как в @+id/priority_text, это то что стили из дизайна, я не утверждал что надо везде использовать именно тот стиль) запутанно написал наверное, все ок

2023-06-26 16:44 UTC, chandrey34 commented on task/src/main/java/com/sinx/task/presentation/PrioritySheetViewModel.kt
> +    fun openBottomSheet() {
в TASK_69 ту же функцию только в Project ты называешь по-другому 
![image](https://github.com/AlexeyGvozdev/TodoApp/assets/104390065/282aef52-3cfb-43b0-958b-dbd9751a8f79)

2023-06-27 08:18 UTC, Fail-Salikhov requested changes

2023-06-27 08:18 UTC, Fail-Salikhov commented on task/src/main/java/com/sinx/task/AddTaskFragment.kt
> +    private lateinit var viewModel: PrioritySheetViewModel
в работе с вью лучше не использовать лейтейнит, так как она не зануляет в он дестрой, это может приводить к багам с вью
https://youtu.be/0nXXUzMyF8c?t=296

2023-06-27 11:57 UTC, simt11 commented on task/src/main/java/com/sinx/task/presentation/PrioritySheetViewModel.kt
> +    fun openBottomSheet() {
Исправил

2023-06-27 11:58 UTC, simt11 commented on task/src/main/java/com/sinx/task/AddTaskFragment.kt
> +    private lateinit var viewModel: PrioritySheetViewModel
Он действительно не зануляется.

При этом, какие могут возникнуть ошибки?

Примеры:

1.   Использование после уничтожения фрагмента: Если вы пытаетесь обратиться к binding после того, как фрагмент был уничтожен (например, в методе onDestroy() или onDetach()), это может привести к UninitializedPropertyAccessException, поскольку ссылка на binding обычно обнуляется в onDestroyView() для предотвращения утечек памяти.
2.   Использование в другом потоке: Если вы пытаетесь обратиться к binding из другого потока, который не является основным потоком пользовательского интерфейса, это может привести к проблемам, поскольку binding и все связанные с ним компоненты пользовательского интерфейса должны использоваться только в основном потоке.

А у нас такого нет. Соответственно и проблем нет. На будующее, мы будем учитывать эти моменты.

2023-07-03 10:28 UTC, Hercules0ff approved these changes

2023-07-04 15:01 UTC, Fail-Salikhov commented on task/src/main/java/com/sinx/task/AddTaskFragment.kt
> +    private lateinit var viewModel: PrioritySheetViewModel
https://bimlibik.github.io/posts/kotlin-lateinit-and-lazy/ 
в части статьи "Но почему стоит избегать?" детальнее описано почему не стоит применять лейтенит. Будет приводить к утечкам памяти.

2023-07-10 14:17 UTC, simt11 commented on task/src/main/java/com/sinx/task/AddTaskFragment.kt
> +    private lateinit var viewModel: PrioritySheetViewModel
Я прочитал статью. Мне она понравилась. 
Так же повторю. Что в нашем приложении не используются сценарии приводящие к утечкам памяти. 
Если считаешь, что нужно избавиться от lateinit превентивно, по типу "Хорошей практики", то можно обсудить с такой точки зрения.

2023-07-10 15:00 UTC, AlexeyGvozdev requested changes

2023-07-10 15:00 UTC, AlexeyGvozdev commented on task/src/main/java/com/sinx/task/AddTaskFragment.kt
> +                when (bundle.getString(Constants.SET_PRIORITY_BUNDLE_KEY)!!) {
можем тут избавиться от `!!`? Иначе у тебя креш будет если строку не вернуть

2023-07-10 15:00 UTC, AlexeyGvozdev commented on task/src/main/java/com/sinx/task/AddTaskFragment.kt
> +                    "green" -> ColorStateList.valueOf(resources.getColor(core_R.color.green))
Давай вынесем в константы для удобства. Или можно попробовать энам класс завести и его использовать

2023-07-10 15:00 UTC, AlexeyGvozdev commented on task/src/main/java/com/sinx/task/AddTaskFragment.kt
> +                    "green" -> ColorStateList.valueOf(resources.getColor(core_R.color.green))
также у тебя в when много повторяющегося кода, а именно `ColorStateList.valueOf(resources.getColor()`
можно из when возвращать ресурс `R.color.name_color

2023-07-10 15:00 UTC, AlexeyGvozdev commented on task/src/main/java/com/sinx/task/TaskListFragment.kt
> +            viewModel.navDeepLinkRequest.collect {
не крит, но можно короче запись сделать `viewModel.navDeepLinkRequest.collect(navController::navigate)`

2023-07-10 15:00 UTC, AlexeyGvozdev commented on task/src/main/java/com/sinx/task/presentation/PrioritySheetViewModel.kt
> +class PrioritySheetViewModel : ViewModel() {
а почему не называется AddTaskViewModel?

2023-07-10 15:00 UTC, AlexeyGvozdev commented on task/src/main/java/com/sinx/task/AddTaskFragment.kt
> +        viewModel = ViewModelProvider(this).get(PrioritySheetViewModel::class.java)
а почему не через `by viewModels` получаем вьюмодель? Кажется тут очень удобно было бы и избавимся от `lateinit`

2023-07-10 15:00 UTC, AlexeyGvozdev commented on task/src/main/java/com/sinx/task/AddTaskFragment.kt
> +                viewModel.onClickAddTask()
название метода у вьюмодели не корректное. Мы же кликаем по приоритету, а метод говорит будто по кнопке создания задачи

2023-07-10 15:00 UTC, AlexeyGvozdev commented on task/src/main/res/layout/bottom_sheet_priority_layout.xml
> +    <ImageView
Так тоже можно и так оставляем. Но посмотри не получилось бы как-то кастомизировать RadioButton c RadioGroup?

2023-07-10 15:00 UTC, AlexeyGvozdev commented on task/src/main/res/values/styles.xml
> +    <style name="ButtonAdd">
Не нашёл где этот стиль используется. Давай удалим если он не нужен

2023-07-10 15:05 UTC, Fail-Salikhov commented on task/src/main/java/com/sinx/task/AddTaskFragment.kt
> +    private lateinit var viewModel: PrioritySheetViewModel
А какой сценарий приводит к утечки?
В статья четко написано, что будет происходит утечка. Я тоже сталкивался с "зависанием" данных, пока вью не занулишь.
И согласен с автором с тем что бы использовать только с дагером.

2023-07-10 15:12 UTC, AlexeyGvozdev requested changes

2023-07-10 15:12 UTC, AlexeyGvozdev commented on app/src/main/res/navigation/task_graph.xml
> +            android:id="@+id/deepLink2"
давай удалим id

2023-07-10 15:12 UTC, AlexeyGvozdev commented on app/src/main/res/navigation/task_graph.xml
> +            android:id="@+id/deepLink3"
тут тоже можно удалить id

2023-07-10 15:12 UTC, AlexeyGvozdev commented on app/src/main/res/navigation/task_graph.xml
> +        <action
Не нашёл где используется этот action. Если нигде, то удаляем

2023-07-11 07:33 UTC, simt11 commented on task/src/main/java/com/sinx/task/AddTaskFragment.kt
> +                when (bundle.getString(Constants.SET_PRIORITY_BUNDLE_KEY)!!) {
Убрал !!

2023-07-11 08:08 UTC, simt11 commented on task/src/main/java/com/sinx/task/AddTaskFragment.kt
> +                    "green" -> ColorStateList.valueOf(resources.getColor(core_R.color.green))
Имеешь ввиду "green" вынести в константу и тд?

2023-07-11 08:17 UTC, simt11 commented on task/src/main/java/com/sinx/task/TaskListFragment.kt
> +            viewModel.navDeepLinkRequest.collect {
Магия просто!!!)))

2023-07-11 10:50 UTC, simt11 commented on task/src/main/java/com/sinx/task/AddTaskFragment.kt
> +        viewModel = ViewModelProvider(this).get(PrioritySheetViewModel::class.java)
Потому, что я не знаю, что это и как работает. Почитаю

2023-07-11 11:07 UTC, simt11 commented on task/src/main/java/com/sinx/task/AddTaskFragment.kt
> +    private lateinit var viewModel: PrioritySheetViewModel
Изменено

2023-07-11 11:16 UTC, simt11 commented on task/src/main/java/com/sinx/task/AddTaskFragment.kt
> +        viewModel = ViewModelProvider(this).get(PrioritySheetViewModel::class.java)
Изменил

2023-07-11 11:19 UTC, simt11 commented on task/src/main/java/com/sinx/task/AddTaskFragment.kt
> +                viewModel.onClickAddTask()
изменил на onClickSelectPriority

2023-07-11 11:24 UTC, simt11 commented on task/src/main/res/values/styles.xml
> +    <style name="ButtonAdd">
Удалил

2023-07-11 11:26 UTC, simt11 commented on app/src/main/res/navigation/task_graph.xml
> +            android:id="@+id/deepLink2"
Удалил

2023-07-11 11:27 UTC, simt11 commented on app/src/main/res/navigation/task_graph.xml
> +            android:id="@+id/deepLink3"
Удалил

2023-07-11 11:32 UTC, simt11 commented on app/src/main/res/navigation/task_graph.xml
> +        <action
Удалил

2023-07-11 11:33 UTC, simt11 commented on task/src/main/java/com/sinx/task/AddTaskFragment.kt
> +                    "green" -> ColorStateList.valueOf(resources.getColor(core_R.color.green))
Сделал

2023-07-12 08:47 UTC, AlexeyGvozdev approved these changes

2023-07-12 08:47 UTC, AlexeyGvozdev commented on app/src/main/res/navigation/task_set_priority_graph.xml
> +            android:id="@+id/deepLink"
тут тоже id надо удалить

2023-07-12 08:51 UTC, simt11 commented on task/src/main/java/com/sinx/task/presentation/PrioritySheetViewModel.kt
> +class PrioritySheetViewModel : ViewModel() {
Изменил название

2023-07-12 08:52 UTC, simt11 commented on task/src/main/res/layout/bottom_sheet_priority_layout.xml
> +    <ImageView
Не смог разобраться, нет сил(

2023-07-12 12:06 UTC, Fail-Salikhov approved these changes

2023-07-12 12:07 UTC, merged