Task 69 refactoring
AlexeyGvozdev/TodoApp pull request #59
Opened 2023-06-21 14:33 UTC by simt11

Рефакторинг

2023-06-21 21:27 UTC, chandrey34 approved these changes

2023-06-22 06:36 UTC, AlexeyGvozdev requested changes

2023-06-22 06:36 UTC, AlexeyGvozdev commented on project/src/main/java/com/sinx/project/BottomSheetAddProjectFragment.kt
> +    private lateinit var binding: BottomSheetAddNewProjectBinding
Почему такой вариант лучше?

2023-06-22 06:36 UTC, AlexeyGvozdev commented on project/src/main/java/com/sinx/project/ProjectFragment.kt
> +        projectListAdapter = ProjectListAdapter()
Тут тоже хочется понять мотивацию этого рефакторинга. Мне не понятно почему теперь стало лучше

2023-06-22 06:36 UTC, AlexeyGvozdev commented on project/src/main/java/com/sinx/project/presentation/ProjectViewModel.kt
> +    fun openBottomSheet() {
Не кажется ли тебе, при таком названии функции фрагмент будет больше приказывать вьюмодели что делать, чем просто сообщать о каком-то клике?

2023-06-22 06:36 UTC, AlexeyGvozdev commented on task/src/main/java/com/sinx/task/AddTaskFragment.kt
> -        _binding = null
расскажи, почему теперь не надо занулять это поле?

2023-06-22 06:36 UTC, AlexeyGvozdev commented on task/src/main/java/com/sinx/task/BottomSheetRepeatFragment.kt
> +        _binding = null
Почему в одном месте ты зануляешь _binding, а вдругом не зануляешь?

2023-06-22 06:36 UTC, AlexeyGvozdev commented on taskList/src/main/java/com/sinx/core/decoration/DividerItemDecorationTask.kt
> +package com.sinx.core.decoration
Вот тут тоже не понятно почему сущность, которая нужна в конкретном модуле и никак не будет переиспользована перемещается в core?

2023-06-22 06:36 UTC, AlexeyGvozdev commented on taskList/src/main/java/com/sinx/taskList/adapter/TaskItemViewHolder.kt
> +            checkBoxTaskPriority.setOnCheckedChangeListener { _, _ ->
не нашёл правило детекта для таких случаев?

2023-06-22 06:45 UTC, simt11 commented on project/src/main/java/com/sinx/project/BottomSheetAddProjectFragment.kt
> +    private lateinit var binding: BottomSheetAddNewProjectBinding
Binding инициализирует в onCreateView, тогда можно не бояться использования до инициализации. При этом мы сокращаем код

2023-06-22 06:58 UTC, simt11 commented on project/src/main/java/com/sinx/project/ProjectFragment.kt
> +        projectListAdapter = ProjectListAdapter()
Здесь мысль, что инициализации собрать в одном месте.

2023-06-22 06:59 UTC, simt11 commented on project/src/main/java/com/sinx/project/presentation/ProjectViewModel.kt
> +    fun openBottomSheet() {
Метод onClickListenerBottomSheet не является слушателем, а скорее выполняет действие. Был еще такой вариант - navigateToBottomSheet

2023-06-22 07:04 UTC, simt11 commented on taskList/src/main/java/com/sinx/core/decoration/DividerItemDecorationTask.kt
> +package com.sinx.core.decoration
Она используется и в проджект и в таск. Разница лишь, что в одном добавлено смещение слева.

2023-06-22 07:32 UTC, simt11 commented on task/src/main/java/com/sinx/task/AddTaskFragment.kt
> -        _binding = null
Lateinit не может быть null. 
Если ты намекаешь на утечку памяти, то скорее всего будет утечка(

2023-06-22 07:47 UTC, simt11 commented on task/src/main/java/com/sinx/task/AddTaskFragment.kt
> -        _binding = null
получается lateinit var binding ViewBinding  корректно использовать в Activity.

2023-06-22 07:49 UTC, simt11 commented on task/src/main/java/com/sinx/task/BottomSheetRepeatFragment.kt
> +        _binding = null
Упустил(

2023-06-22 10:03 UTC, simt11 commented on taskList/src/main/java/com/sinx/taskList/adapter/TaskItemViewHolder.kt
> +            checkBoxTaskPriority.setOnCheckedChangeListener { _, _ ->
Да, я не смог разобраться((

2023-06-22 10:44 UTC, simt11 commented on taskList/src/main/java/com/sinx/taskList/adapter/TaskItemViewHolder.kt
> +            checkBoxTaskPriority.setOnCheckedChangeListener { _, _ ->
Нашел UnusedVariable, UnusedPrivateProperty. Но не понял как добавить чтоб заработало. 

пока получаю
> Task :detektAll FAILED
Property 'style>UnusedPrivateProperty' is misspelled or does not exist.
Property 'style>UnusedTypeArguments' is misspelled or does not exist.
Property 'style>UnusedVariable' is misspelled or does not exist.

2023-06-23 10:12 UTC, simt11 commented on project/src/main/java/com/sinx/project/presentation/ProjectViewModel.kt
> +    fun openBottomSheet() {
Изменил название на onClickAddProject. Чтобы Фрагмент не указывал, что должна делать ViewModel.

2023-06-23 10:14 UTC, simt11 commented on taskList/src/main/java/com/sinx/core/decoration/DividerItemDecorationTask.kt
> +package com.sinx.core.decoration
удалил остаток сущности в task

2023-06-26 16:53 UTC, chandrey34 commented on task/src/main/java/com/sinx/task/TaskListFragment.kt
>                  ContextCompat.getDrawable(requireContext(), core_R.drawable.divider)
в TASK 66 мы удалили файл R.drawable.divider, соответственно будет конфликт когда я смержу свою ветку.
Кажется не стоит удалять DividerItemDecorationTask и DividerItemDecorationProject и оставить их на своих местах, т.к там используется разная отрисовка по дизайну, в TASK 66 я как раз их и менял немного, избавившись от ресурса divider

2023-06-26 16:55 UTC, chandrey34 requested changes
.

2023-06-27 08:19 UTC, Fail-Salikhov requested changes

2023-06-27 08:19 UTC, Fail-Salikhov commented on project/src/main/java/com/sinx/project/BottomSheetAddProjectFragment.kt
> +    private lateinit var binding: BottomSheetAddNewProjectBinding
в работе с вью лучше не использовать лейтейнит, так как она не зануляет в он дестрой, это может приводить к багам с вью
https://youtu.be/0nXXUzMyF8c?t=296

2023-06-27 11:24 UTC, simt11 commented on task/src/main/java/com/sinx/task/TaskListFragment.kt
>                  ContextCompat.getDrawable(requireContext(), core_R.drawable.divider)
Откатил изменения.

2023-06-27 11:24 UTC, simt11 commented on taskList/src/main/java/com/sinx/core/decoration/DividerItemDecorationTask.kt
> +package com.sinx.core.decoration
Откатил изменения

2023-06-27 11:34 UTC, simt11 commented on project/src/main/java/com/sinx/project/BottomSheetAddProjectFragment.kt
> +    private lateinit var binding: BottomSheetAddNewProjectBinding
Он действительно не зануляется.

При этом, какие могут возникнуть ошибки? 

Примеры:
    1) Использование после уничтожения фрагмента: Если вы пытаетесь обратиться к binding после того, как фрагмент был уничтожен (например, в методе onDestroy() или onDetach()), это может привести к UninitializedPropertyAccessException, поскольку ссылка на binding обычно обнуляется в onDestroyView() для предотвращения утечек памяти.

   2) Использование в другом потоке: Если вы пытаетесь обратиться к binding из другого потока, который не является основным потоком пользовательского интерфейса, это может привести к проблемам, поскольку binding и все связанные с ним компоненты пользовательского интерфейса должны использоваться только в основном потоке.

А у нас такого нет. Соответственно и проблем нет. На будующее, мы будем учитывать эти моменты.

2023-07-04 15:00 UTC, Fail-Salikhov commented on project/src/main/java/com/sinx/project/BottomSheetAddProjectFragment.kt
> +    private lateinit var binding: BottomSheetAddNewProjectBinding
https://bimlibik.github.io/posts/kotlin-lateinit-and-lazy/ 
в части статьи "Но почему стоит избегать?" детальнее описано почему не стоит применять лейтенит. Будет приводить к утечкам памяти.

2023-07-10 14:17 UTC, simt11 commented on project/src/main/java/com/sinx/project/BottomSheetAddProjectFragment.kt
> +    private lateinit var binding: BottomSheetAddNewProjectBinding
Я прочитал статью. Мне она понравилась. 
Так же повторю. В нашем приложении не используются сценарии приводящие к утечкам памяти. 
Если считаешь, что нужно избавиться от lateinit превентивно, по типу "Хорошей практики", то можно обсудить с такой точки зрения.

2023-07-10 15:03 UTC, Fail-Salikhov commented on project/src/main/java/com/sinx/project/BottomSheetAddProjectFragment.kt
> +    private lateinit var binding: BottomSheetAddNewProjectBinding
А какой сценарий приводит к утечки?
В статья четко написано, что будет происходит утечка.  Я тоже сталкивался с "зависанием" данных, пока вью не занулишь.
И согласен с автором с тем что бы использовать только с дагером.

2023-07-11 11:40 UTC, simt11 commented on project/src/main/java/com/sinx/project/BottomSheetAddProjectFragment.kt
> +    private lateinit var binding: BottomSheetAddNewProjectBinding
Изменил

2023-07-11 11:42 UTC, simt11 commented on task/src/main/java/com/sinx/task/AddTaskFragment.kt
> -        _binding = null
Изменил

2023-07-11 13:26 UTC, Fail-Salikhov approved these changes

2023-07-11 15:58 UTC, AlexeyGvozdev approved these changes

2023-07-12 08:40 UTC, chandrey34 approved these changes

2023-07-12 08:41 UTC, merged