task-33 rebase
AlexeyGvozdev/TodoApp pull request #61
Opened 2023-06-30 14:03 UTC by Fail-Salikhov

2023-07-10 10:54 UTC, simt11 approved these changes

2023-07-17 10:32 UTC, Hercules0ff approved these changes

2023-07-20 17:21 UTC, AlexeyGvozdev requested changes

2023-07-20 17:21 UTC, AlexeyGvozdev commented on project/src/main/java/com/sinx/project/domain/AddNewProgectUseCaseImpl.kt
>  internal class AddNewProjectUseCaseImpl(private val projectRepository: ProjectRepository) :
dispatcher: Dispatcher = Dispatcher.IO

2023-07-20 17:21 UTC, AlexeyGvozdev commented on project/src/main/java/com/sinx/project/domain/AddNewProgectUseCaseImpl.kt
> +    override suspend fun invoke(newProject: ProjectListModel) {
override suspend fun invoke(newProject: ProjectListModel) = withContext(dispatcher) {

2023-07-20 17:23 UTC, AlexeyGvozdev requested changes

2023-07-20 17:23 UTC, AlexeyGvozdev commented on coreDB/coreDbApi/src/main/java/com/sinx/coredbinterface/dao/ProjectDAO.kt
> +    suspend fun addTask(projectDB: ProjectDbModel)
task -> project

2023-08-07 17:37 UTC, AlexeyGvozdev approved these changes

2023-08-07 17:37 UTC, AlexeyGvozdev commented on project/src/main/java/com/sinx/project/di/ProjectComponent.kt
> +    @Component.Builder
Попробуй через @Component.Factory

2023-08-21 17:27 UTC, merged