TASK-71 Adding screen with details of the task
AlexeyGvozdev/TodoApp pull request #66
Opened 2023-07-31 18:28 UTC by Vladislava05

1. Сверстала экран
2. Сделала переход к нему по клику на область таска
3. При открытии экрана проставляется название и дата таска, по которому кликали

2023-08-07 16:26 UTC, Fail-Salikhov approved these changes

2023-08-07 17:15 UTC, AlexeyGvozdev commented
git commit --amend

2023-08-07 17:32 UTC, AlexeyGvozdev requested changes

2023-08-07 17:32 UTC, AlexeyGvozdev commented on app/src/main/res/navigation/task_graph.xml
> +            android:id="@+id/deepLink3"
можно удалить id

2023-08-07 17:32 UTC, AlexeyGvozdev commented on task/src/main/res/layout/inner_task_layout.xml
> +            android:background="@android:color/transparent"
заведи в ресурсах цвет transparent и замени тут

2023-08-07 17:32 UTC, AlexeyGvozdev commented on task/src/main/java/com/sinx/task/TaskListFragment.kt
> +                val request = NavDeepLinkRequest.Builder.fromUri(
сделай через viewmodel

2023-08-07 17:32 UTC, AlexeyGvozdev commented on task/src/main/res/layout/inner_task_layout.xml
> +
удали пустую строку

2023-08-21 12:45 UTC, AlexeyGvozdev approved these changes

2023-08-21 12:45 UTC, AlexeyGvozdev commented on task/src/main/java/com/sinx/task/InnerTaskFragment.kt
> +class InnerTaskFragment : Fragment() {
Давай его как-то назовём по другому. TaskFragment, DetailsTaskFragment или TaskInfoFragment

2023-08-21 12:46 UTC, AlexeyGvozdev requested changes
Покажи дизайнеру экран

2023-10-30 12:56 UTC, AlexeyGvozdev requested changes

2023-10-30 12:56 UTC, AlexeyGvozdev commented on taskList/src/main/java/com/sinx/taskList/model/GetTaskListUseCase.kt
> +    override suspend operator fun invoke() = repository.listTasksFlow().map {
вот это верни как было

2023-11-01 09:00 UTC, AlexeyGvozdev approved these changes

2023-11-01 09:11 UTC, merged